module.exports = [
    {
        firstName: 'Albert',
        lastName: 'Anderson',
        birthday: '1-1-06',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 3,
        clothesDonated: 10,
        furnitureDonated: 1,
    },
    {
        firstName: 'Alan',
        lastName: 'Anderson',
        birthday: '1-1-09',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 2,
        clothesDonated: 9,
        furnitureDonated: 2,
    },
    {
        firstName: 'Bethanie',
        lastName: 'Benson',
        birthday: '1-1-07',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 20,
        clothesDonated: 1,
        furnitureDonated: 0,
    },
    {
        firstName: 'Belinda',
        lastName: 'Benson',
        birthday: '1-1-09',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 6,
        clothesDonated: 6,
        furnitureDonated: 3,
    },
    {
        firstName: 'Christopher',
        lastName: 'Chadwick',
        birthday: '1-1-11',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 4,
        furnitureDonated: 1,
    },
    {
        firstName: 'Chelsea',
        lastName: 'Chadwick',
        birthday: '1-1-11',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 4,
        furnitureDonated: 1,
    },
    {
        firstName: 'Darlene',
        lastName: 'Douglas',
        birthday: '1-1-13',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 1,
        clothesDonated: 1,
        furnitureDonated: 1,
    },
    {
        firstName: 'David',
        lastName: 'Douglas',
        birthday: '1-1-10',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 6,
        clothesDonated: 23,
        furnitureDonated: 3,
    },
    {
        firstName: 'Freddy',
        lastName: 'Franklin',
        birthday: '1-1-17',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 2,
        clothesDonated: 25,
        furnitureDonated: 1,
    },
    {
        firstName: 'Francis',
        lastName: 'Franklin',
        birthday: '1-1-15',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 0,
        clothesDonated: 4,
        furnitureDonated: 1,
    },
    {
        firstName: 'Erin',
        lastName: 'Edwards',
        birthday: '1-1-18',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 20,
        clothesDonated: 20,
        furnitureDonated: 3,
    },
    {
        firstName: 'Eugene',
        lastName: 'Edwards',
        birthday: '1-1-14',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 10,
        furnitureDonated: 3,
    },
    {
        firstName: 'Geoff',
        lastName: 'Granger',
        birthday: '1-1-19',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 0,
        clothesDonated: 0,
        furnitureDonated: 0,
    },
    {
        firstName: 'Gregg',
        lastName: 'Granger',
        birthday: '1-1-17',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 10,
        furnitureDonated: 3,
    },
    {
        firstName: 'Harry',
        lastName: 'Harrison',
        birthday: '1-1-16',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 5,
        clothesDonated: 5,
        furnitureDonated: 1,
    },
    {
        firstName: 'Igor',
        lastName: 'Inglasias',
        birthday: '1-1-19',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 0,
        clothesDonated: 0,
        furnitureDonated: 0,
    },
    {
        firstName: 'Ivan',
        lastName: 'EInglasias',
        birthday: '1-1-15',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 5,
        clothesDonated: 5,
        furnitureDonated: 2,
    },
    {
        firstName: 'Jennifer',
        lastName: 'Jackson',
        birthday: '1-1-08',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 20,
        clothesDonated: 20,
        furnitureDonated: 3,
    },
    {
        firstName: 'Kevin',
        lastName: 'King',
        birthday: '1-1-08',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 30,
        clothesDonated: 40,
        furnitureDonated: 6,
    },
    {
        firstName: 'Kelsey',
        lastName: 'King',
        birthday: '1-1-06',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 7,
        clothesDonated: 18,
        furnitureDonated: 4,
    },
    {
        firstName: 'Lindsay',
        lastName: 'Lewis',
        birthday: '1-1-16',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 13,
        clothesDonated: 19,
        furnitureDonated: 1,
    },
    {
        firstName: 'Linda',
        lastName: 'Lewis',
        birthday: '1-1-09',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 10,
        furnitureDonated: 3,
    },
];
