module.exports = [
    {
        firstName: 'Albert',
        lastName: 'Anderson',
        birthday: '2006-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 3,
        clothesDonated: 10,
        furnitureDonated: 1,
        ParentId: 1,
    },
    {
        firstName: 'Alan',
        lastName: 'Anderson',
        birthday: '2009-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 2,
        clothesDonated: 9,
        furnitureDonated: 2,
        ParentId: 1,
    },
    {
        firstName: 'Bethanie',
        lastName: 'Benson',
        birthday: '2007-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 20,
        clothesDonated: 1,
        furnitureDonated: 0,
        ParentId: 2,
    },
    {
        firstName: 'Belinda',
        lastName: 'Benson',
        birthday: '2009-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 6,
        clothesDonated: 6,
        furnitureDonated: 3,
        ParentId: 2,
    },
    {
        firstName: 'Christopher',
        lastName: 'Chadwick',
        birthday: '2011-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 4,
        furnitureDonated: 1,
        ParentId: 3,
    },
    {
        firstName: 'Chelsea',
        lastName: 'Chadwick',
        birthday: '2011-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 4,
        furnitureDonated: 1,
        ParentId: 3,
    },
    {
        firstName: 'Darlene',
        lastName: 'Douglas',
        birthday: '2013-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 1,
        clothesDonated: 1,
        furnitureDonated: 1,
        ParentId: 4,
    },
    {
        firstName: 'David',
        lastName: 'Douglas',
        birthday: '2010-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 6,
        clothesDonated: 23,
        furnitureDonated: 3,
        ParentId: 4,
    },
    {
        firstName: 'Freddy',
        lastName: 'Franklin',
        birthday: '2017-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 2,
        clothesDonated: 25,
        furnitureDonated: 1,
        ParentId: 6,
    },
    {
        firstName: 'Francis',
        lastName: 'Franklin',
        birthday: '2015-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 0,
        clothesDonated: 4,
        furnitureDonated: 1,
        ParentId: 6,
    },
    {
        firstName: 'Erin',
        lastName: 'Edwards',
        birthday: '2018-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 20,
        clothesDonated: 20,
        furnitureDonated: 3,
        ParentId: 5,
    },
    {
        firstName: 'Eugene',
        lastName: 'Edwards',
        birthday: '2014-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 10,
        furnitureDonated: 3,
        ParentId: 5,
    },
    {
        firstName: 'Geoff',
        lastName: 'Granger',
        birthday: '2019-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 0,
        clothesDonated: 0,
        furnitureDonated: 0,
        ParentId: 7,
    },
    {
        firstName: 'Gregg',
        lastName: 'Granger',
        birthday: '2017-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 10,
        furnitureDonated: 3,
        ParentId: 7,
    },
    {
        firstName: 'Harry',
        lastName: 'Harrison',
        birthday: '2016-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 5,
        clothesDonated: 5,
        furnitureDonated: 1,
        ParentId: 8,
    },
    {
        firstName: 'Igor',
        lastName: 'Inglasias',
        birthday: '2019-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 0,
        clothesDonated: 0,
        furnitureDonated: 0,
        ParentId: 9,
    },
    {
        firstName: 'Ivan',
        lastName: 'Inglasias',
        birthday: '2015-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 5,
        clothesDonated: 5,
        furnitureDonated: 2,
        ParentId: 9,
    },
    {
        firstName: 'Jennifer',
        lastName: 'Jackson',
        birthday: '2008-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 20,
        clothesDonated: 20,
        furnitureDonated: 3,
        ParentId: 10,
    },
    {
        firstName: 'Kevin',
        lastName: 'King',
        birthday: '2008-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 30,
        clothesDonated: 40,
        furnitureDonated: 6,
        ParentId: 11,
    },
    {
        firstName: 'Kelsey',
        lastName: 'King',
        birthday: '2006-01-01',
        gender: 'male',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 7,
        clothesDonated: 18,
        furnitureDonated: 4,
        ParentId: 11,
    },
    {
        firstName: 'Lindsay',
        lastName: 'Lewis',
        birthday: '2016-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 13,
        clothesDonated: 19,
        furnitureDonated: 1,
        ParentId: 12,
    },
    {
        firstName: 'Linda',
        lastName: 'Lewis',
        birthday: '2009-01-01',
        gender: 'female',
        receiveToys: true,
        receiveClothes: true,
        receiveFurniture: true,
        donateToys: true,
        donateClothes: true,
        donateFurniture: true,
        toysDonated: 10,
        clothesDonated: 10,
        furnitureDonated: 3,
        ParentId: 12,
    },
];
