module.exports = [
    {
        firstName: 'Amanda',
        lastName: 'Anderson',
        UserId: 1,
        address1: '1234 Anderson Ave',
        city: 'Auburn',
        state: 'WA',
        zipCode: '98001',
    },
    {
        firstName: 'Bill',
        lastName: 'Benson',
        UserId: 2,
        address1: '1234 Benson Ave',
        city: 'Bellevue',
        state: 'WA',
        zipCode: '98004',
    },
    {
        firstName: 'Cynthia',
        lastName: 'Chadwick',
        UserId: 3,
        address1: '1234 Chadwick Ave',
        city: 'Carnation',
        state: 'WA',
        zipCode: '98014',
    },
    {
        firstName: 'Douglas',
        lastName: 'Douglas',
        UserId: 4,
        address1: '1234 Douglas Ave',
        city: 'Duvall',
        state: 'WA',
        zipCode: '98019',
    },
    {
        firstName: 'Edwin',
        lastName: 'Edwards',
        UserId: 5,
        address1: '1234 Edwards Ave',
        city: 'Enumclaw',
        state: 'WA',
        zipCode: '98022',
    },
    {
        firstName: 'Fredrique',
        lastName: 'Franklin',
        UserId: 6,
        address1: '1234 Franklin Ave',
        city: 'Fall City',
        state: 'WA',
        zipCode: '98024',
    },
    {
        firstName: 'Gerdie',
        lastName: 'Granger',
        UserId: 7,
        address1: '1234 Granger Ave',
        city: 'Gold Bar',
        state: 'WA',
        zipCode: '98251',
    },
    {
        firstName: 'Harriette',
        lastName: 'Harrison',
        UserId: 8,
        address1: '1234 Harrison Ave',
        city: 'Hazel Dell',
        state: 'WA',
        zipCode: '98665',
    },
    {
        firstName: 'Ingrid',
        lastName: 'Inglesias',
        UserId: 9,
        address1: '1234 Inglesias Ave',
        city: 'Index',
        state: 'WA',
        zipCode: '98256',
    },
    {
        firstName: 'Janet',
        lastName: 'Jackson',
        UserId: 10,
        address1: '1234 Jackson Ave',
        city: 'Jamestown',
        state: 'WA',
        zipCode: '98382',
    },
    {
        firstName: 'Kelly',
        lastName: 'King',
        UserId: 11,
        address1: '1234 King Ave',
        city: 'Klickitat',
        state: 'WA',
        zipCode: '98628',
    },
    {
        firstName: 'Lenny',
        lastName: 'Lewis',
        UserId: 12,
        address1: '1234 Lewis Ave',
        city: 'Lebam',
        state: 'WA',
        zipCode: '98554',
    },
];
