module.exports = [
    {
        userName: 'amanda@anderson.com',
        password: 'password',
        address1: '1234 Anderson Ave',
        city: 'Auburn',
        state: 'WA',
        zipcode: '98001',
    },
    {
        userName: 'Bill@benson.com',
        password: 'password',
        address1: '1234 Benson Ave',
        city: 'Bellevue',
        state: 'WA',
        zipcode: '98004',
    },
    {
        userName: 'Cynthia@Chadwick.com',
        password: 'password',
        address1: '1234 Chadwick Ave',
        city: 'Carnation',
        state: 'WA',
        zipcode: '98014',
    },
    {
        userName: 'Douglas@Douglas.com',
        password: 'password',
        address1: '1234 Douglas Ave',
        city: 'Duvall',
        state: 'WA',
        zipcode: '98019',
    },
    {
        userName: 'Edwin@Edwards.com',
        password: 'password',
        address1: '1234 Edwards Ave',
        city: 'Enumclaw',
        state: 'WA',
        zipcode: '98022',
    },
    {
        userName: 'Fredrique@Franklin.com',
        password: 'password',
        address1: '1234 Franklin Ave',
        city: 'Fall City',
        state: 'WA',
        zipcode: '98024',
    },
    {
        userName: 'Gerdie@Granger.com',
        password: 'password',
        address1: '1234 Granger Ave',
        city: 'Gold Bar',
        state: 'WA',
        zipcode: '98251',
    },
    {
        userName: 'Harriette@Harrison.com',
        password: 'password',
        address1: '1234 Harrison Ave',
        city: 'Hazel Dell',
        state: 'WA',
        zipcode: '98665',
    },
    {
        userName: 'Ingrid@Inglesias.com',
        password: 'password',
        address1: '1234 inglesias Ave',
        city: 'Index',
        state: 'WA',
        zipcode: '98256',
    },
    {
        userName: 'Janet@Jackson.com',
        password: 'password',
        address1: '1234 Jackson Ave',
        city: 'Jamestown',
        state: 'WA',
        zipcode: '98382',
    },
    {
        userName: 'Kelly@King.com',
        password: 'password',
        address1: '1234 King Ave',
        city: 'Klickitat',
        state: 'WA',
        zipcode: '98628',
    },
    {
        userName: 'Lenny@Lewis.com',
        password: 'password',
        address1: '1234 Lewis Ave',
        city: 'Lebam',
        state: 'WA',
        zipcode: '98554',
    },
];
